
Turn 4
================================================================
error: communication error with bot: read failed, errno was: 0 (Success)
Last input received was:


Bot error output was:
Traceback (most recent call last):
  File "MyBot.py", line 58, in <module>
    logging.error("1" + collision_free_move)
TypeError: must be str, not bool

