
Turn 2
================================================================
error: communication error with bot: read failed, errno was: 0 (Success)
Last input received was:


Bot error output was:
Traceback (most recent call last):
  File "MyBot.py", line 72, in <module>
    collision_free_move = intendMove(ship, random.choice([ Direction.North, Direction.South, Direction.East, Direction.West ]))
  File "MyBot.py", line 27, in intendMove
    game_map[ship.position].mark_safe(ship)
TypeError: mark_safe() takes 1 positional argument but 2 were given

