
Turn 2
================================================================
error: communication error with bot: read failed, errno was: 0 (Success)
Last input received was:


Bot error output was:
Traceback (most recent call last):
  File "MyBot.py", line 67, in <module>
    collision_free_move = intendMove(ship, random.choice([ Direction.North, Direction.South, Direction.East, Direction.West ]))
  File "MyBot.py", line 25, in intendMove
    if override or (ship.halite < (targetCell.halite_amount * 0.1) and not targetCell.is_occupied and not targetCell.has_structure):
AttributeError: 'Ship' object has no attribute 'halite'

