
Turn 2
================================================================
error: communication error with bot: read failed, errno was: 0 (Success)
Last input received was:


Bot error output was:
Traceback (most recent call last):
  File "MyBot.py", line 51, in <module>
    command_queue.append(intendMove(ship, random.choice([ Direction.North, Direction.South, Direction.East, Direction.West ])))
NameError: name 'intendMove' is not defined

